# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.track_list = QtWidgets.QListWidget(self.centralwidget)
        self.track_list.setGeometry(QtCore.QRect(10, 30, 421, 411))
        self.track_list.setObjectName("track_list")
        self.openbtn = QtWidgets.QPushButton(self.centralwidget)
        self.openbtn.setGeometry(QtCore.QRect(10, 450, 81, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.openbtn.setFont(font)
        self.openbtn.setObjectName("openbtn")
        self.savebtn = QtWidgets.QPushButton(self.centralwidget)
        self.savebtn.setGeometry(QtCore.QRect(110, 450, 81, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.savebtn.setFont(font)
        self.savebtn.setObjectName("savebtn")
        self.trackslabel = QtWidgets.QLabel(self.centralwidget)
        self.trackslabel.setGeometry(QtCore.QRect(10, 0, 421, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.trackslabel.setFont(font)
        self.trackslabel.setObjectName("trackslabel")
        self.propertieslabel = QtWidgets.QLabel(self.centralwidget)
        self.propertieslabel.setGeometry(QtCore.QRect(440, 0, 161, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.propertieslabel.setFont(font)
        self.propertieslabel.setObjectName("propertieslabel")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(220, 460, 221, 21))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.processlabel = QtWidgets.QLabel(self.centralwidget)
        self.processlabel.setGeometry(QtCore.QRect(460, 460, 361, 21))
        self.processlabel.setText("")
        self.processlabel.setObjectName("processlabel")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(880, 460, 111, 21))
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setProperty("value", 100)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(440, 30, 551, 411))
        self.listWidget.setObjectName("listWidget")
        self.speakerlabel = QtWidgets.QLabel(self.centralwidget)
        self.speakerlabel.setGeometry(QtCore.QRect(840, 455, 30, 30))
        self.speakerlabel.setText("")
        self.speakerlabel.setObjectName("speakerlabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.openbtn.setText(_translate("MainWindow", "Abrir"))
        self.savebtn.setText(_translate("MainWindow", "Guardar"))
        self.trackslabel.setText(_translate("MainWindow", "Lista de Tracks"))
        self.propertieslabel.setText(_translate("MainWindow", "Propiedades"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
